ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120601.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120601.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120602.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120602.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120603.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120603.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120604.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120604.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120605.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120605.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120606.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120606.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120607.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120607.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120608.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120608.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120609.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120609.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120610.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120610.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120611.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120611.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120612.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120612.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120613.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120613.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120614.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120614.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120615.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120615.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120616.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120616.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120617.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120617.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120618.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120618.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120619.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120619.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120620.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120620.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120621.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120621.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120622.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120622.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120623.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120623.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120624.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120624.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120625.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120625.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120626.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120626.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120627.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120627.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120628.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120628.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120629.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120629.nc 
ncks -h -C -O -x -v ssh_it /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120630.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120630.nc 
