ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120501.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120501.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120502.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120502.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120503.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120503.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120504.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120504.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120505.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120505.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120506.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120506.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120507.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120507.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120508.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120508.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120509.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120509.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120510.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120510.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120511.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120511.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120512.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120512.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120513.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120513.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120514.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120514.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120515.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120515.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120516.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120516.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120517.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120517.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120518.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120518.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120519.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120519.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120520.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120520.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120521.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120521.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120522.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120522.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120523.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120523.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120524.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120524.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120525.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120525.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120526.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120526.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120527.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120527.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120528.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120528.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120529.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120529.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120530.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120530.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120531.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120531.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120601.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120601.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120602.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120602.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120603.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120603.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120604.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120604.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120605.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120605.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120606.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120606.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120607.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120607.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120608.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120608.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120609.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120609.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120610.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120610.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120611.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120611.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120612.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120612.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120613.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120613.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120614.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120614.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120615.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120615.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120616.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120616.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120617.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120617.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120618.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120618.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120619.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120619.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120620.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120620.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120621.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120621.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120622.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120622.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120623.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120623.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120624.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120624.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120625.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120625.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120626.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120626.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120627.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120627.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120628.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120628.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120629.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120629.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120630.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120630.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120701.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120701.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120702.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120702.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120703.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120703.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120704.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120704.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120705.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120705.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120706.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120706.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120707.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120707.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120708.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120708.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120709.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120709.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120710.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120710.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120711.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120711.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120712.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120712.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120713.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120713.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120714.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120714.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120715.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120715.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120716.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120716.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120717.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120717.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120718.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120718.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120719.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120719.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120720.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120720.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120721.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120721.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120722.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120722.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120723.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120723.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120724.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120724.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120725.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120725.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120726.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120726.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120727.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120727.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120728.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120728.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120729.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120729.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120730.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120730.nc 
ncks -C -O -x -v ssh_cor,ssh_igw /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120731.nc /bettik/bellemva/MITgcm/MITgcm_filtered_final/MITgcm_filt_20120731.nc 
